waypoints:
  - position:
      x: 1.6
      y: 1.6
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0    # 0째 spre est
  - position:
      x: 2.4
      y: 1.6
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.707
      w: 0.707  # 90째 spre nord
  - position:
      x: 2.4
      y: 2.4
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 1.0
      w: 0.0    # 180째 spre vest
  - position:
      x: 1.6
      y: 2.4
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: -0.707
      w: 0.707  # 270째 spre sud