amcl:
  ros__parameters:
    use_sim_time: False
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "base_link"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 1.2
    laser_max_range: 8.0
    laser_min_range: 0.03
    laser_model_type: "likelihood_field"
    max_beams: 400
    max_particles: 4000
    min_particles: 800
    odom_frame_id: "odom"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    save_pose_rate: 0.5
    sigma_hit: 0.08
    tf_broadcast: true
    transform_tolerance: 0.15
    update_min_a: 0.05
    update_min_d: 0.10
    z_hit: 0.65
    z_max: 0.05
    z_rand: 0.35
    z_short: 0.05
    scan_topic: scan
    map_topic: map    
    set_initial_pose: true
    always_reset_initial_pose: true
    first_map_only: false   
    initial_pose:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0

amcl_map_client:
  ros__parameters:
    use_sim_time: False

amcl_rclcpp_node:
  ros__parameters:
    use_sim_time: False

behavior_server:
  ros__parameters:
    enable_stamped_cmd_vel: true 
    local_costmap_topic: local_costmap/costmap_raw
    local_footprint_topic: local_costmap/published_footprint
    global_costmap_topic: global_costmap/costmap_raw
    global_footprint_topic: global_costmap/published_footprint
    cycle_frequency: 8.0
    behavior_plugins:
      ["spin", "backup", "drive_on_heading", "wait", "assisted_teleop"]
    spin:
      plugin: "nav2_behaviors::Spin"
    backup:
      plugin: "nav2_behaviors::BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors::DriveOnHeading"
    wait:
      plugin: "nav2_behaviors::Wait"
    assisted_teleop:
      plugin: "nav2_behaviors::AssistedTeleop"
    local_frame: odom
    global_frame: map
    robot_base_frame: base_link
    transform_timeout: 0.2
    simulate_ahead_time: 3.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 2.2

bt_navigator:
  ros__parameters:
    enable_stamped_cmd_vel: true 
    use_sim_time: False
    global_frame: map
    robot_base_frame: base_link
    odom_topic: "/platform/odom/filtered"
    bt_loop_duration: 10
    default_server_timeout: 20
    
    # Behavior trees pentru diferite scenarii
    default_nav_to_pose_bt_xml: "$(find-pkg-share amr2ax_nav2)/behavior_trees/battery_aware_navigation.xml"
    default_nav_through_poses_bt_xml: "$(find-pkg-share amr2ax_nav2)/behavior_trees/battery_aware_waypoint_navigation.xml"
    default_dynamic_follow_bt_xml: "$(find-pkg-share amr2ax_nav2)/behavior_trees/dynamic_object_following.xml"
    always_reload_bt_xml: false
    
    navigators: [navigate_to_pose, navigate_through_poses, dynamic_follow]
    navigate_to_pose:
      plugin: nav2_bt_navigator::NavigateToPoseNavigator
    navigate_through_poses:
      plugin: nav2_bt_navigator::NavigateThroughPosesNavigator
    dynamic_follow:
      plugin: nav2_bt_navigator::NavigateToPoseNavigator




bt_navigator_rclcpp_node:
  ros__parameters:
    use_sim_time: False


controller_server:
  ros__parameters:
    use_sim_time: False
    enable_stamped_cmd_vel: true 
    controller_frequency: 30.0
    min_x_velocity_threshold: 0.03
    min_y_velocity_threshold: 0.03
    min_theta_velocity_threshold: 0.3
    failure_tolerance: 1.0

    progress_checker_plugin: "progress_checker"
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.3
      movement_time_allowance: 15.0

    goal_checker_plugin: "goal_checker"
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.2
      yaw_goal_tolerance: 0.2
      stateful: True

    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_mppi_controller::MPPIController"
      time_steps: 30
      model_dt: 0.10
      batch_size: 350
      vx_std: 0.2
      vy_std: 0.2
      wz_std: 0.4
      vx_max: 4.0
      vx_min: -4.0
      vy_max: 1.7
      wz_max: 4.5
      ax_max: 4.0
      ax_min: -5.0
      ay_max: 4.0
      az_max: 5.5
      iteration_count: 1
      prune_distance: 1.2 # de testat cu val mai mici
      transform_tolerance: 0.15
      temperature: 0.2
      gamma: 0.015
      robot_mass: 5.0
      motion_model: "DiffDrive"
      visualize: false
      reset_period: 1.0 # (only in Humble)
      regenerate_noises: false
      TrajectoryVisualizer:
        trajectory_step: 5
        time_step: 3
      critics: ["ConstraintCritic", "CostCritic", "GoalCritic", "GoalAngleCritic", "PathAlignCritic", "PathFollowCritic", "PathAngleCritic", "PreferForwardCritic"]
      ConstraintCritic:
        enabled: true
        cost_power: 1
        cost_weight: 4.0
      GoalCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        threshold_to_consider: 1.4
      GoalAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 3.0
        threshold_to_consider: 0.5
      PreferForwardCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        threshold_to_consider: 0.5
      CostCritic:
        enabled: true
        cost_power: 1
        cost_weight: 2.5
        critical_cost: 250.0
        consider_footprint: true
        collision_cost: 800000.0
        near_goal_distance: 1.0
        trajectory_point_step: 2
      PathAlignCritic:
        enabled: true
        cost_power: 1
        cost_weight: 14.0
        max_path_occupancy_ratio: 0.05
        trajectory_point_step: 4
        threshold_to_consider: 0.5
        offset_from_furthest: 20
        use_path_orientations: true  # Use orientations from Smac Planner
      PathFollowCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        offset_from_furthest: 5
        threshold_to_consider: 1.4
      PathAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 2.0
        offset_from_furthest: 4
        threshold_to_consider: 0.5
        max_angle_to_furthest: 1.0
        mode: 2  # Use orientations from Smac Planner
      
#controller_server_rclcpp_node:
#  ros__parameters:
#    use_sim_time: False      

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 10.0
      publish_frequency: 5.0
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: False
      rolling_window: true
      always_send_full_costmap: True
      width: 3
      height: 3
      resolution: 0.025 #0.05
      #robot_radius: 0.18
      footprint: "[ [0.250, 0.218], [0.250, -0.218], [-0.250, -0.218], [-0.250, 0.218] ]"
      footprint_padding: 0.01 #0.04
      plugins: ["voxel_layer", "inflation_layer"]
      #plugins: ["obstacle_layer", "voxel_layer", "inflation_layer"]
      #plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: True
        cost_scaling_factor: 3.0
        inflation_radius: 0.55       
        #inflation_radius: 0.45 # 0.55
        #cost_scaling_factor: 11.0
#      obstacle_layer:
#        plugin: "nav2_costmap_2d::ObstacleLayer"
#        enabled: True
#        observation_sources: scan
#        scan:
#          topic: /scan
#          max_obstacle_height: 2.0
#          clearing: True
#          marking: True
#          data_type: "LaserScan"
#          raytrace_max_range: 6.0
#          raytrace_min_range: 0.03
#          obstacle_max_range: 4.0
#          obstacle_min_range: 0.03
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        publish_voxel_map: True
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 2.0
        mark_threshold: 0
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 6.0
          raytrace_min_range: 0.03       # ðŸ”¥ CHANGED from 0.05!
          obstacle_max_range: 4.0
          obstacle_min_range: 0.03       # ðŸ”¥ CHANGED from 0.05!                  
#      voxel_layer:
#        plugin: "nav2_costmap_2d::VoxelLayer"
#        enabled: True
#        publish_voxel_map: True
#        footprint_clearing_enabled: True
#        origin_z: 0.0
#        z_resolution: 0.05
#        z_voxels: 12
#        max_obstacle_height: 2.0
#        mark_threshold: 0
#        observation_sources: scan
#        observation_sources: scan vx53l5
#        scan:
#          topic: /scan
#          min_obstacle_height: 0.254
#          max_obstacle_height: 2.0
#          clearing: True
#          marking: True
#          data_type: "LaserScan"
#          raytrace_max_range: 4.24  # max diagonal of 3m costmap
#          raytrace_min_range: 0.0
#          obstacle_max_range: 2.5
#          obstacle_min_range: 0.0
#        vx53l5:
#          topic: /pointcloud
#          min_obstacle_height: 0.05
#          max_obstacle_height: 0.7
#          clearing: True
#          marking: True
#          data_type: "PointCloud2"
#          raytrace_max_range: 2.0
#          raytrace_min_range: 0.5
#          obstacle_max_range: 1.5
#          obstacle_min_range: 0.5  
#      static_layer:
#        plugin: "nav2_costmap_2d::StaticLayer"
#        enabled: True
#        map_subscribe_transient_local: True
      #always_send_full_costmap: True
  local_costmap_client:
    ros__parameters:
      use_sim_time: False
  local_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False     

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 3.0
      publish_frequency: 2.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: False
      footprint: "[ [0.250, 0.218], [0.250, -0.218], [-0.250, -0.218], [-0.250, 0.218] ]"
      resolution: 0.03
      track_unknown_space: true
      
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 8.0
          raytrace_min_range: 0.03       # ðŸ”¥ CHANGED from 0.05!
          obstacle_max_range: 7.0
          obstacle_min_range: 0.03       # ðŸ”¥ CHANGED from 0.05!
      
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 5.0
  global_costmap_client:
    ros__parameters:
      use_sim_time: False
  global_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False

      
map_server:
  ros__parameters:
    use_sim_time: False
    # Overridden in launch by the "map" launch configuration or provided default value.
    # To use in yaml, remove the default "map" value in the tb3_simulation_launch.py file & provide full path to map below.
#    yaml_filename: "cb201.yaml"
    yaml_filename: "cb204v1.yaml"    

map_saver:
  ros__parameters:
    use_sim_time: False
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: True

planner_server:
  ros__parameters:
    use_sim_time: False
    expected_planner_frequency: 5.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_smac_planner::SmacPlannerHybrid"
      downsample_costmap: false          # whether or not to downsample the map
      downsampling_factor: 1              # multiplier for the resolution of the costmap layer (e.g. 2 on a 5cm costmap would be 10cm)
      tolerance: 0.60                     # increase tolerance to accept nearby valid endpoints when goal lies on/near obstacles
      allow_unknown: true                 # allow traveling in unknown space
      max_iterations: 800000             # maximum total iterations to search for before failing (in case unreachable), set to -1 to disable
      max_on_approach_iterations: 1000    # Maximum number of iterations after within tolerances to continue to try to find exact solution
      max_planning_time: 8.0              # max time in s for planner to plan, smooth
      motion_model_for_search: "REEDS_SHEPP"    # Hybrid-A* Dubin, Redds-Shepp
      angle_quantization_bins: 64         # Number of angle bins for search
      analytic_expansion_ratio: 3.0       # The ratio to attempt analytic expansions during search for final approach.
      analytic_expansion_max_length: 2.5  # For Hybrid/Lattice nodes: The maximum length of the analytic expansion to be considered valid to prevent unsafe shortcutting
      analytic_expansion_max_cost: 200.0  # The maximum single cost for any part of an analytic expansion to contain and be valid, except when necessary on approach to goal
      analytic_expansion_max_cost_override: false  #  Whether or not to override the maximum cost setting if within critical distance to goal (ie probably required)
      minimum_turning_radius: 0.37        # minimum turning radius in m of path / vehicle
      reverse_penalty: 1.5                # Penalty to apply if motion is reversing, must be => 1
      change_penalty: 0.15                 # Penalty to apply if motion is changing directions (L to R), must be >= 0
      non_straight_penalty: 1.1           # Penalty to apply if motion is non-straight, must be => 1
      cost_penalty: 1.8                   # Penalty to apply to higher cost areas when adding into the obstacle map dynamic programming distance expansion heuristic. This drives the robot more towards the center of passages. A value between 1.3 - 3.5 is reasonable.
      retrospective_penalty: 0.012
      lookup_table_size: 4.0              # Size of the dubin/reeds-sheep distance window to cache, in meters.
      cache_obstacle_heuristic: false     # Cache the obstacle map dynamic programming distance expansion heuristic between subsiquent replannings of the same goal location. Dramatically speeds up replanning performance (40x) if costmap is largely static.
      debug_visualizations: false         # For Hybrid nodes: Whether to publish expansions on the /expansions topic as an array of poses (the orientation has no meaning) and the path's footprints on the /planned_footprints topic. WARNING: heavy to compute and to display, for debug only as it degrades the performance.
      use_quadratic_cost_penalty: False
      downsample_obstacle_heuristic: True
      allow_primitive_interpolation: False
      smooth_path: True                   # If true, does a simple and quick smoothing post-processing to the path

      smoother:
        max_iterations: 800
        w_smooth: 0.3
        w_data: 0.2
        tolerance: 1.0e-6
        do_refinement: true
        refinement_num: 2

#planner_server_rclcpp_node:
#  ros__parameters:
#    use_sim_time: False

smoother_server:
  ros__parameters:
    use_sim_time: False
    smoother_plugins: ["simple_smoother"]
    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 1.0e-10
      max_its: 1000
      do_refinement: True


waypoint_follower:
  ros__parameters:
    use_sim_time: False
    loop_rate: 25
    stop_on_failure: false
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 2000


velocity_smoother:
  ros__parameters:
    enable_stamped_cmd_vel: true 
    use_sim_time: False
    smoothing_frequency: 8.0
    scale_velocities: False
    feedback: "OPEN_LOOP"
    max_velocity: [4.0, 0.0, 3.2]
    min_velocity: [-4.0, 0.0, -3.2]
    max_accel: [4.0, 0.0, 4.2]
    max_decel: [-4.0, 0.0, -4.2]
    odom_topic: "/platform/odom/filtered"
    odom_duration: 0.15
    deadband_velocity: [0.02, 0.0, 0.05]
    velocity_timeout: 1.5
