amcl:
  ros__parameters:
    enable_stamped_cmd_vel: true 
    use_sim_time: false
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "base_link"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 1.2
    laser_max_range: 8.0
    laser_min_range: 0.03
    laser_model_type: "likelihood_field"
    max_beams: 300
    max_particles: 4000
    min_particles: 800
    odom_frame_id: "odom"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    save_pose_rate: 0.5
    sigma_hit: 0.08
    tf_broadcast: true
    transform_tolerance: 0.20
    update_min_a: 0.05
    update_min_d: 0.10
    z_hit: 0.65
    z_max: 0.05
    z_rand: 0.35
    z_short: 0.05
    scan_topic: scan
    map_topic: map    
    set_initial_pose: true
    always_reset_initial_pose: true
    initial_pose:
      x: 1.0
      y: -1.27
      z: 0.00
      yaw: 0.0
      

behavior_server:
  ros__parameters:
    enable_stamped_cmd_vel: true 
    local_costmap_topic: local_costmap/costmap_raw
    local_footprint_topic: local_costmap/published_footprint
    global_costmap_topic: global_costmap/costmap_raw
    global_footprint_topic: global_costmap/published_footprint
    cycle_frequency: 8.0
    behavior_plugins:
      ["spin", "backup", "drive_on_heading", "wait", "assisted_teleop"]
    spin:
      plugin: "nav2_behaviors::Spin"
    backup:
      plugin: "nav2_behaviors::BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors::DriveOnHeading"
    wait:
      plugin: "nav2_behaviors::Wait"
    assisted_teleop:
      plugin: "nav2_behaviors::AssistedTeleop"
    local_frame: odom
    global_frame: map
    robot_base_frame: base_link
    transform_tolerance: 0.2
    simulate_ahead_time: 3.0
    # SYNCED with diff_drive_controller
    max_rotational_vel: 6.0
    min_rotational_vel: 0.6
    rotational_acc_lim: 8.2

bt_navigator:
  ros__parameters:
    enable_stamped_cmd_vel: true 
    use_sim_time: false
    global_frame: map
    robot_base_frame: base_link
    odom_topic: "odom"
    enable_stamped_cmd_vel: true
    bt_loop_duration: 10
    default_server_timeout: 20

    navigators: ["navigate_to_pose", "navigate_through_poses"]
    navigate_to_pose:
      plugin: "nav2_bt_navigator::NavigateToPoseNavigator"
    navigate_through_poses:
      plugin: "nav2_bt_navigator::NavigateThroughPosesNavigator"
    
    error_code_names: ["follow_path_error_code", "compute_path_error_code"]


controller_server:
  ros__parameters:
    use_sim_time: false
    enable_stamped_cmd_vel: true 
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.03
    min_y_velocity_threshold: 0.03
    min_theta_velocity_threshold: 0.1
    failure_tolerance: 0.0

    progress_checker_plugin: "progress_checker"
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.15
      movement_time_allowance: 20.0

    goal_checker_plugin: "goal_checker"
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.20
      yaw_goal_tolerance: 0.20
      stateful: true

    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_mppi_controller::MPPIController"
      time_steps: 30
      model_dt: 0.10
      batch_size: 350
      vx_std: 0.2
      vy_std: 0.0
      wz_std: 0.3
      # SYNCED with diff_drive_controller limits
      vx_max: 6.0
      vx_min: -6.0
      vy_max: 0.0           # No lateral movement (diff-drive)
      wz_max: 3.0
      ax_max: 6.0
      ax_min: -6.0
      ay_max: 0.0
      az_max: 8.2
      iteration_count: 1
      prune_distance: 1.2
      transform_tolerance: 0.15
      temperature: 0.2
      gamma: 0.015
      robot_mass: 5.0
      motion_model: "DiffDrive"
      visualize: false
      reset_period: 1.0
      regenerate_noises: false
      TrajectoryVisualizer:
        trajectory_step: 5
        time_step: 3
      critics: ["ConstraintCritic", "CostCritic", "GoalCritic", "GoalAngleCritic", "PathAlignCritic", "PathFollowCritic", "PathAngleCritic", "PreferForwardCritic"]
      ConstraintCritic:
        enabled: true
        cost_power: 1
        cost_weight: 4.0
      GoalCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        threshold_to_consider: 1.4
      GoalAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 3.0
        threshold_to_consider: 0.5
      PreferForwardCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        threshold_to_consider: 0.5
      CostCritic:
        enabled: true
        cost_power: 1
        cost_weight: 2.5
        critical_cost: 250.0
        consider_footprint: true
        collision_cost: 800000.0
        near_goal_distance: 1.0
        trajectory_point_step: 2
      PathAlignCritic:
        enabled: true
        cost_power: 1
        cost_weight: 14.0
        max_path_occupancy_ratio: 0.05
        trajectory_point_step: 4
        threshold_to_consider: 0.5
        offset_from_furthest: 20
        use_path_orientations: true
      PathFollowCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        offset_from_furthest: 5
        threshold_to_consider: 1.4
      PathAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 2.0
        offset_from_furthest: 4
        threshold_to_consider: 0.5
        max_angle_to_furthest: 1.0
        mode: 2
      

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 5.0
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: false
      rolling_window: true
      always_send_full_costmap: true
      width: 3
      height: 3
      resolution: 0.025
      footprint: "[ [0.235, 0.220], [0.235, -0.220], [-0.235, -0.220], [-0.235, 0.220] ]"
      footprint_padding: 0.01
      plugins: ["obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: true
          marking: true
          data_type: "LaserScan"
          raytrace_max_range: 8.0
          raytrace_min_range: 0.03
          obstacle_max_range: 7.0
          obstacle_min_range: 0.03
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: true
        inflation_radius: 0.42
        cost_scaling_factor: 11.0
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        enabled: true
        map_subscribe_transient_local: true
  local_costmap_client:
    ros__parameters:
      use_sim_time: false
  local_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: false     

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 3.0
      publish_frequency: 2.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: false
      footprint: "[ [0.235, 0.220], [0.235, -0.220], [-0.235, -0.220], [-0.235, 0.220] ]"
      footprint_padding: 0.01
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: true
          marking: true
          data_type: "LaserScan"
          raytrace_max_range: 8.0
          raytrace_min_range: 0.03
          obstacle_max_range: 7.0
          obstacle_min_range: 0.03
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        enabled: true
        map_subscribe_transient_local: true
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: true
        inflation_radius: 0.42
        cost_scaling_factor: 11.0
      always_send_full_costmap: true
  global_costmap_client:
    ros__parameters:
      use_sim_time: false
  global_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: false

      
map_server:
  ros__parameters:
    enable_stamped_cmd_vel: true 
    use_sim_time: false
    yaml_filename: "cb204v1.yaml"    

map_saver:
  ros__parameters:
    enable_stamped_cmd_vel: true 
    use_sim_time: false
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: true

planner_server:
  ros__parameters:
    enable_stamped_cmd_vel: true 
    use_sim_time: false
    expected_planner_frequency: 5.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_smac_planner::SmacPlannerHybrid"
      downsample_costmap: false
      downsampling_factor: 1
      tolerance: 0.60
      allow_unknown: true
      max_iterations: 800000
      max_on_approach_iterations: 1000
      max_planning_time: 8.0
      motion_model_for_search: "REEDS_SHEPP"
      angle_quantization_bins: 64
      analytic_expansion_ratio: 3.0
      analytic_expansion_max_length: 2.5
      analytic_expansion_max_cost: 200.0
      analytic_expansion_max_cost_override: false
      minimum_turning_radius: 0.20
      reverse_penalty: 1.5
      change_penalty: 0.15
      non_straight_penalty: 1.1
      cost_penalty: 1.8
      retrospective_penalty: 0.012
      lookup_table_size: 4.0
      cache_obstacle_heuristic: false
      debug_visualizations: false
      use_quadratic_cost_penalty: false
      downsample_obstacle_heuristic: true
      allow_primitive_interpolation: false
      smooth_path: true

      smoother:
        max_iterations: 800
        w_smooth: 0.3
        w_data: 0.2
        tolerance: 1.0e-6
        do_refinement: true
        refinement_num: 2

smoother_server:
  ros__parameters:
    enable_stamped_cmd_vel: true 
    use_sim_time: false
    smoother_plugins: ["simple_smoother"]
    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 1.0e-10
      max_its: 1000
      do_refinement: true


waypoint_follower:
  ros__parameters:
    enable_stamped_cmd_vel: true 
    use_sim_time: false
    loop_rate: 25
    stop_on_failure: false
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: true
      waypoint_pause_duration: 2000

velocity_smoother:
  ros__parameters:
    enable_stamped_cmd_vel: true 
    use_sim_time: false
    smoothing_frequency: 20.0
    scale_velocities: false
    feedback: "OPEN_LOOP"
    # SYNCED with diff_drive_controller limits
    # Format: [linear.x, linear.y, angular.z]
    max_velocity: [4.0, 0.0, 4.0]
    min_velocity: [-4.0, 0.0, -4.0]
    max_accel: [8.0, 0.0, 8.2]
    max_decel: [-8.0, 0.0, -8.2]
    odom_topic: "odom"
    odom_duration: 0.15
    deadband_velocity: [0.02, 0.0, 0.05]
    velocity_timeout: 1.5

collision_monitor:
  ros__parameters:
    enable_stamped_cmd_vel: true 
    use_sim_time: false
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    cmd_vel_in_topic: "cmd_vel_smoothed"
    cmd_vel_out_topic: "cmd_vel"
    state_topic: "collision_monitor_state"
    transform_tolerance: 0.2
    source_timeout: 2.0
    base_shift_correction: true
    stop_pub_timeout: 2.0
    
    polygons: ["FootprintApproach"]
    
    FootprintApproach:
      type: "polygon"
      action_type: "approach"
      footprint_topic: "/local_costmap/published_footprint"
      time_before_collision: 1.5
      simulation_time_step: 0.1
      min_points: 4
      visualize: true
      enabled: true
    
    observation_sources: ["scan"]
    
    scan:
      type: "scan"
      topic: "scan"
      min_height: 0.05
      max_height: 0.4
      enabled: true

# Lifecycle Manager
lifecycle_manager_navigation:
  ros__parameters:
    use_sim_time: false
    autostart: true
    node_names: ['controller_server', 'planner_server', 'behavior_server', 
                 'bt_navigator', 'waypoint_follower', 'velocity_smoother']