amcl:
  ros__parameters:
    use_sim_time: False
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "base_link"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 100.0
    laser_min_range: -1.0
    laser_model_type: "likelihood_field"
    max_beams: 60
    max_particles: 2000
    min_particles: 500
    odom_frame_id: "odom"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    save_pose_rate: 0.5
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 0.7
    update_min_a: 0.2
    update_min_d: 0.25
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05
    scan_topic: scan
    map_topic: map    
    set_initial_pose: true
    always_reset_initial_pose: true
    first_map_only: false   
    initial_pose:
      x: 0.050
      y: 0.050
      z: 0.00
      yaw: 0.00
#cb201  pose (1719488543.819332): 0.021 0.078 -0.005
#co011  pose (1719484657.568559): 0.259 0.018 0.006

#0.759 -0.802 -1.556

#0.790 -1.208 -1.572


#cb204-hol v2 0.215 -1.163 -2.355
#cb204-hol 0.190 -1.278 -2.324 (statie)
#cb204-hol 0.730 -0.653 -2.271 (in fata statiei) 
#G01 0.601 -0.662 0.796
#G02  2.932 1.966 -2.318
#G03 0.730 -0.653 -2.271 (in fata statiei - down) 
#G04 0.190 -1.278 -2.324 (statie - up)
#G05 0.730 -0.653 -2.271 (in fata statiei - down) 
#G06 0.601 -0.662 0.796

# -1.106 -0.025 -0.062
# -2.493 -0.026 -0.008

#0.219 -0.011 -0.705

#1.545 -0.737 1.571
#0.019 0.003 1.586

# -1.169 0.267 0.032

#0.05, 0.79) to (-0.01, 0.98)
#(0.04, 0.91) to (-0.02, 0.52)
#(-0.00, 0.61) to (0.41, 0.30)
#(-0.00, 0.61) to (0.41, 0.30)
#0.52, 0.30) to (1.74, -0.09)
# (0.01, 0.76) to (-0.00, 0.37)
amcl_map_client:
  ros__parameters:
    use_sim_time: False

amcl_rclcpp_node:
  ros__parameters:
    use_sim_time: False

behavior_server:
  ros__parameters:
    enable_stamped_cmd_vel: true 
    local_costmap_topic: local_costmap/costmap_raw
    local_footprint_topic: local_costmap/published_footprint
    global_costmap_topic: global_costmap/costmap_raw
    global_footprint_topic: global_costmap/published_footprint
    cycle_frequency: 5.0
    behavior_plugins:
      ["spin", "backup", "drive_on_heading", "wait", "assisted_teleop"]
    spin:
      plugin: "nav2_behaviors::Spin"
    backup:
      plugin: "nav2_behaviors::BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors::DriveOnHeading"
    wait:
      plugin: "nav2_behaviors::Wait"
    assisted_teleop:
      plugin: "nav2_behaviors::AssistedTeleop"
    local_frame: odom
    global_frame: map
    robot_base_frame: base_link
    transform_timeout: 0.1
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 2.2

bt_navigator:
  ros__parameters:
    enable_stamped_cmd_vel: true 
    use_sim_time: False
    global_frame: map
    robot_base_frame: base_link
    odom_topic: "/platform/odom/filtered"
    bt_loop_duration: 10
    default_server_timeout: 20
    navigators: [navigate_to_pose, navigate_through_poses]
    navigate_to_pose:
      plugin: nav2_bt_navigator::NavigateToPoseNavigator
    navigate_through_poses:
      plugin: nav2_bt_navigator::NavigateThroughPosesNavigator

bt_navigator_rclcpp_node:
  ros__parameters:
    use_sim_time: False


controller_server:
  ros__parameters:
    use_sim_time: True
    enable_stamped_cmd_vel: true 
    controller_frequency: 5.0
    min_x_velocity_threshold: 0.03
    min_y_velocity_threshold: 0.03
    min_theta_velocity_threshold: 0.3
    failure_tolerance: 2.0

    progress_checker_plugin: "progress_checker"
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0

    goal_checker_plugin: "goal_checker"
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.15
      yaw_goal_tolerance: 0.15
      stateful: True

    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"

      # Velocity/accelaration limits also have to be adjusted in the velocity smoother
      desired_linear_vel: 0.33
      lookahead_dist: 0.6
      min_lookahead_dist: 0.3
      max_lookahead_dist: 0.9
      lookahead_time: 1.0
      transform_tolerance: 0.1
      use_velocity_scaled_lookahead_dist: true
      min_approach_linear_velocity: 0.1
      approach_velocity_scaling_dist: 0.5
      use_collision_detection: false
      max_allowed_time_to_collision_up_to_carrot: 2.5

      use_regulated_linear_velocity_scaling: true # Whether to use the regulated features for path curvature (e.g. slow on high curvature paths).
      use_cost_regulated_linear_velocity_scaling: false # Whether to use the regulated features for proximity to obstacles (e.g. slow in close proximity to obstacles).

      regulated_linear_scaling_min_radius: 0.5
      regulated_linear_scaling_min_speed: 0.2
      allow_reversing: true
      use_rotate_to_heading: true
      rotate_to_heading_min_angle: 0.785
      # it is only used when rotating to heading (use_rotate_to_heading)
      # for some reason rotate_to_heading_angular_vel is ignored and robot rotates with
      # max_angular_accel/10. angular velocity (that's why it is set to higher value)
      max_angular_accel: 2.3
      rotate_to_heading_angular_vel: 1.2
      max_robot_pose_search_dist: 10.0
      use_interpolation: true
      
controller_server_rclcpp_node:
  ros__parameters:
    use_sim_time: False      

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: False
      rolling_window: true
      always_send_full_costmap: True
      width: 3
      height: 3
      resolution: 0.03 #0.05
      #robot_radius: 0.18
      footprint: "[ [0.250, 0.220], [0.250, -0.220], [-0.250, -0.220], [-0.250, 0.220] ]"
      footprint_padding: 0.03 #0.04
#      plugins: ["voxel_layer", "inflation_layer"]
      plugins: ["obstacle_layer", "voxel_layer", "inflation_layer"]
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: True
        inflation_radius: 0.50 # 0.55
        cost_scaling_factor: 3.0
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
#      voxel_layer:
#        plugin: "nav2_costmap_2d::VoxelLayer"
#        enabled: True
#        publish_voxel_map: True
#        footprint_clearing_enabled: True
#        origin_z: 0.0
#        z_resolution: 0.05
#        z_voxels: 12
#        max_obstacle_height: 2.0
#        mark_threshold: 0
#        observation_sources: scan
#        observation_sources: scan vx53l5
#        scan:
#          topic: /scan
#          min_obstacle_height: 0.254
#          max_obstacle_height: 2.0
#          clearing: True
#          marking: True
#          data_type: "LaserScan"
#          raytrace_max_range: 4.24  # max diagonal of 3m costmap
#          raytrace_min_range: 0.0
#          obstacle_max_range: 2.5
#          obstacle_min_range: 0.0
#        vx53l5:
#          topic: /pointcloud
#          min_obstacle_height: 0.05
#          max_obstacle_height: 0.7
#          clearing: True
#          marking: True
#          data_type: "PointCloud2"
#          raytrace_max_range: 2.0
#          raytrace_min_range: 0.5
#          obstacle_max_range: 1.5
#          obstacle_min_range: 0.5  
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        enabled: True
        map_subscribe_transient_local: True
      #always_send_full_costmap: True
  local_costmap_client:
    ros__parameters:
      use_sim_time: False
  local_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False     

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: False
      footprint: "[ [0.250, 0.220], [0.250, -0.220], [-0.250, -0.220], [-0.250, 0.220] ]"
      footprint_padding: 0.01
      #robot_radius: 0.33
      #resolution: 0.05
      #track_unknown_space: true
      #plugins: ["static_layer", "voxel_layer", "inflation_layer"]
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
#      voxel_layer:
#        plugin: "nav2_costmap_2d::VoxelLayer"
#        enabled: True
#        publish_voxel_map: False
#        footprint_clearing_enabled: True
#        origin_z: 0.0
#        z_resolution: 0.05
#        z_voxels: 12
#        max_obstacle_height: 2.0
#        mark_threshold: 0
#        observation_sources: lidar
#        lidar:
#          topic: scan
#          min_obstacle_height: 0.254
#          max_obstacle_height: 0.8
#          clearing: True
#          marking: True
#          data_type: "LaserScan"
#          raytrace_max_range: 11.0
#          raytrace_min_range: 0.0
#          obstacle_max_range: 10.0
#          obstacle_min_range: 0.2
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        enabled: True
        map_subscribe_transient_local: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: True
        inflation_radius: 0.50
        cost_scaling_factor: 3.0
      always_send_full_costmap: True
  global_costmap_client:
    ros__parameters:
      use_sim_time: True
  global_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: True

      
map_server:
  ros__parameters:
    use_sim_time: False
    # Overridden in launch by the "map" launch configuration or provided default value.
    # To use in yaml, remove the default "map" value in the tb3_simulation_launch.py file & provide full path to map below.
#    yaml_filename: "cb201.yaml"
    yaml_filename: "cb204v1.yaml"    

map_saver:
  ros__parameters:
    use_sim_time: False
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: True

planner_server:
  ros__parameters:
    use_sim_time: True
    expected_planner_frequency: 1.0

    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner::NavfnPlanner"
      tolerance: 0.2
      use_astar: false
      allow_unknown: true

planner_server_rclcpp_node:
  ros__parameters:
    use_sim_time: False

smoother_server:
  ros__parameters:
    use_sim_time: False


waypoint_follower:
  ros__parameters:
    use_sim_time: True
    loop_rate: 20
    stop_on_failure: false
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 2000

velocity_smoother:
  ros__parameters:
    enable_stamped_cmd_vel: true 
    use_sim_time: True
    smoothing_frequency: 5.0
    scale_velocities: False
    feedback: "OPEN_LOOP"
    max_velocity: [1.0, 0.0, 1.2]
    min_velocity: [-1.0, 0.0, -1.2]
    max_accel: [1.0, 0.0, 1.2]
    max_decel: [-1.0, 0.0, -1.2]
    odom_topic: "/platform/odom/filtered"
    odom_duration: 0.1
    deadband_velocity: [0.0, 0.0, 0.0]
    velocity_timeout: 1.0
